### ISSUE TITLE
No use of locale in reverseQuery (FR only)

### ISSUE THREAD

**Issue by ici-be** [geo6/geocoder-php-urbis-provider#4]
I was unable to fix it yet, but the value of $query->getLocale() is null in reverseQuery.

The previous UrbIS API did accept null as language value (and returned french), but the new UrbIS API causes an error because of it. That's why I added a fallback "fr" value in my pull request;

**Comment by jbelien** [comment]
If I understand correctly your PR #3 fixes this right ?

**Comment by jbelien** [comment]
If I'm not wrong, the *new* API also accepts an empty value for `language` !

Example : http://geoservices.irisnet.be/localization/Rest/Localize/getaddressfromxy?json={%22language%22%3A%22%22%2C%22point%22%3A{%22x%22%3A%22149785%22%2C%22y%22%3A%22170561%22}%2C%22SRS_In%22%3A%2231370%22}

**Comment by ici-be** [comment]
My PR works, but always retrieves informations in french (as did yours). I
made a small change to force FR because "null" is no longer accepted. I'll
try to find how to manage NL results asap, didn't find yet why the locale
value was null :-/
